# Generated by Django 5.1a1 on 2024-07-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['pk'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'изображение продукта', 'verbose_name_plural': 'Изображения продуктов'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='ozon_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vk_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wb_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='yandex_id',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='supplier_url',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='vk_id',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст вместо изображения'),
        ),
    ]
