# Generated by Django 5.1a1 on 2024-07-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_orderitem_options_alter_productimages_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
    ]
