# Generated by Django 5.1a1 on 2024-07-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_productimages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина покупателя', 'verbose_name_plural': 'Корзины покупателей'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый заказ', 'Новый заказ'), ('Сборка заказа', 'Сборка заказа'), ('Доставляется', 'Доставляется'), ('Ожидает выдачи в магазине', 'Ожидает выдачи в магазине'), ('Доставлен', 'Доставлен'), ('Выдан', 'Выдан'), ('Отменен', 'Отменен')], default='Новый заказ', max_length=32, verbose_name='Статус заказа'),
        ),
    ]
