# Generated by Django 5.1b1 on 2024-07-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_cart_options_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='ozon_id',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='vk_id',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='wb_id',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='yandex_id',
        ),
    ]
