# Generated by Django 5.1b1 on 2024-07-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_productcategory_ozon_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='ozon_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='OZON ID'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='vk_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='VK ID'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='wb_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Wildberries ID'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='yandex_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Яндекс ID'),
        ),
    ]
