# Generated by Django 5.1b1 on 2024-07-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productcategory_ozon_id_productcategory_vk_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='ozon_id',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='vk_id',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='wb_id',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='yandex_id',
        ),
    ]
